name: CI

on:
  pull_request:
    branches: [ final_codes ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Install dependencies
      run: npm install

    - name: Tests
      run: yarn test
   
    - name: Check lint
      run: yarn lint

